---
title: "Antibiotic recovery"
output: html_notebook
---

We start by reading in the original data and the annotations. Luckily, the authors have made the 
data available on https://github.com/CSB5/Recovery_Determinants_Study so we can use that data
here.

## Data from Singapore

```{r}
library(data.table)
library(openxlsx)
map = c(INITIAL = "pre", CLOSING = "during", POST = "post")

sg <- fread("https://github.com/CSB5/Recovery_Determinants_Study/raw/master/Data/Suppl1_SG.txt")
labels <- fread("https://github.com/CSB5/Recovery_Determinants_Study/raw/master/Data/TariniLabels_edit.txt")
sg <- melt(sg, id.vars = "Sample_Name", variable.name = "species", value.name = "percentage")
sg[, "stage" := factor(map[tstrsplit(Sample_Name, "_")[[4]]], levels = map)]
sg[, "sample_id" := tstrsplit(Sample_Name, "_")[[1]]]
sg[, "country" := "Singapore"]
sg <- sg[, .(percentage = mean(percentage), Sample_Name = Sample_Name[1]), 
         by=c("sample_id", "stage", "country", "species")]
sg
```

## Data from Canada

```{r}
library(data.table)
map = c(E0 = "pre", E7 = "during", E90 = "post")

ca <- fread("https://github.com/CSB5/Recovery_Determinants_Study/raw/master/Data/Suppl1_CA_Final.txt")
ca <- melt(ca, id.vars = "Index", variable.name = "species", value.name = "percentage")
setnames(ca, "Index", "Sample_Name")
ca[, "stage" := factor(map[tstrsplit(Sample_Name, "P\\d+")[[2]]], levels = map)]
ca[, "sample_id" := tstrsplit(Sample_Name, "E")[[1]]]
ca[, "species" := gsub("^s__", "", species)]
ca[, "country" := "Canada"]
ca <- ca[, .(percentage = mean(percentage), Sample_Name = Sample_Name[1]), 
         by=c("sample_id", "stage", "country", "species")]
ca
```

Let's merge the two data sets.

```{r}

abundances <- rbind(sg, ca)
abundances <- labels[, .(ID, Status)][abundances, on = c(ID = "Sample_Name")][!is.na(Status) & Status != "C"]
counts <- unique(abundances[, .(sample_id, stage)])[, table(sample_id)]
#abundances <- abundances[sample_id %chin% names(counts)[counts == 3]]
abundances[, table(country, Status)]
```

## Alpha Diversity

Finally we'll calculate the Shannon index for each sample and visualize.

```{r}
library(vegan)
library(ggplot2)
theme_set(theme_minimal())

diversity <- abundances[, .(diversity = diversity(percentage)), 
                        by = c("stage", "sample_id", "Status", "country")]

ggplot(diversity, aes(x=stage, y=diversity, color = Status, group=sample_id)) + 
  geom_point() +
  geom_line() +
  facet_wrap(~ country) + labs(x="antibiotics", y="α-diversity [Shannon]", color="recovery")
ggsave("alpha_diversity.png", width=6, height=4, dpi=300)
```

## Save to Excel

```{r}
singapore <- dcast(abundances[country == "Singapore"], 
                   ID + sample_id + stage + Status ~ species, 
                   value.var = "percentage")[order(sample_id, stage)]
canada <- dcast(abundances[country == "Canada"], 
                ID + sample_id + stage + Status ~ species, 
                value.var = "percentage")[order(sample_id, stage)]
keystone_vars <- c("ID", "sample_id", "stage", "Status", 
                   "Bacteroides_thetaiotaomicron", "Bifidobacterium_adolescentis")
openxlsx::write.xlsx(
  list(
    `Alpha Diversity (wide)` = dcast(diversity[order(sample_id, stage)], 
                              sample_id + Status + country ~ stage,
                              value.var = "diversity"),
    `Alpha Diversity (long)` = diversity[order(sample_id, stage)],
    `Keystone Taxa Singapore` = singapore[, keystone_vars, with=F],
    `Keystone Taxa Canada` = canada[, keystone_vars, with=F],
    Singapore = singapore, 
    Canada = canada
  ),
  file = "antibiotics.xlsx",
  overwrite = TRUE
)
```