---
title: "C. difficile FMT"
output: html_notebook
---

Let's start by reading the generated data and collapsing it on the genus level.

```{r}
library(mbtools)

ps <- readRDS("phyloseq.rds")
ps <- tax_glom(ps, "Genus")
sample_names(ps) <- gsub("_1", "", sample_names(ps))
ps <- subset_samples(ps, sample_sums(ps) > 1000)
```

No we will assemble the metadata and attach it.

```{r}
cdi <- fread("cdi_metadata.csv")
cdi[, "Tissue" := "feces"]
skin <- fread("skin_metadata.csv")
skin[, "animations_subject" := "skin"]
skin[, "animations_gradient" := -(1:.N)]
skin[, "description" := "sample from skin"]
sdata <- rbind(cdi, skin, fill=T) %>% as.data.frame()
rownames(sdata) <- sdata$Run
sample_data(ps) <- sdata
ps
```



Let's get the phyla composition and drop very small abundance phyla.

```{r}
phyla <- tax_glom(ps, "Phylum")
taxa_names(phyla) <- tax_table(phyla)[, "Phylum"]
phyla <- subset_taxa(phyla, taxa_sums(phyla) > 100)
phyla
```
## Time courses

```{r, fig.width=12, fig.height=8}
relative <- plot_taxa(phyla, only_data = T)
relative <- as.data.table(sdata)[relative, on = c(Run = "sample")]
relative <- relative[, .(relative = mean(reads)), by = c("animations_gradient", "animations_subject", "taxa", "description")]
names(relative) <- c("days_since_fmt", "subject", "phylum", "description", "relative")
total_ord <- relative[, sum(relative, na.rm = TRUE), by = "phylum"][order(-V1), phylum]

dont_show <- c("skin", "Patient", "Donor")
ggplot(relative, aes(x=factor(days_since_fmt), y=relative, fill=factor(phylum, levels=rev(total_ord)))) + 
  geom_bar(stat="identity", position="fill") + 
  facet_wrap(~ subject, scales="free_x") + 
  scale_fill_brewer(palette = "Paired", direction = -1) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "time since FMT [days]", y="", fill="phylum")
ggsave("time_courses_all.png", width=12, height=8, dpi=300)
```

## Ordination

```{r}
theme_set(theme_minimal())

ord <- ps %>% rarefy_even_depth() %>% ordinate(method="PCoA")
plot_ordination(ps, ord, color = "animations_subject", label = "day_relative_to_fmt") +
  labs(color = "sample source")
ggsave("pcoa.png", width=6, height=4, dpi=300)

ord_nice = as.data.frame(ord$vectors[, 1:2])
ord_nice <- cbind(ord_nice, sample_data(ps)[, c("animations_subject", "Tissue", "description", "day_relative_to_fmt")])
names(ord_nice) <- c("x", "y", "subject", "tissue", "description", "days_since_fmt")
ord_nice
```

## Export to Excel

```{r}
library(openxlsx)

write.xlsx(list(
  `phyla percentages` = dcast(
    relative, subject + days_since_fmt + description ~ phylum, 
    value.var = "relative", fill=0),
  `Bray-Curtis ordination` = ord_nice
), "cdiff_fmt.xlsx", overwrite = T)
```